language: csharp
solution: ./src/Lux.sln
mono:
  - nightly
install:
  - nuget restore ./src/Lux.sln
  - nuget install NUnit.Runners -Version 3.0.1 -OutputDirectory testrunner
script:
  - xbuild ./src/Lux.sln /p:Configuration=Release
  - mono \"./testrunner/NUnit.Console.3.0.1/tools/nunit-console.exe\" \"/exclude:ExcludeBuildAgent\" \"./src/Lux.Tests/bin/Release/Lux.Tests.dll\"
notifications:
  email: false
