language: csharp
solution: ./src/Lux.sln
mono:
  - nightly
install:
  - nuget restore ./src/Lux.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild ./src/Lux.sln /p:Configuration=Release
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./src/Lux.Tests/bin/Release/Lux.Tests.dll /exclude:ExcludeBuildAgent|IntegrationTests
notifications:
  email: false
